import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styled from "styled-components";
import TT from "../components/translation/TT";
import Fa from "../components/translation/Fa";
import En from "../components/translation/En";

export default function Home() {
  return (
    <>
      <Head>
        <title>Darsoon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb_Black.woff2" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb_Bold.woff2" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb_Light.woff2" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb_Medium.woff2" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb_UltraLight.woff2" as="font" crossOrigin="" />
        <link rel="preload" href="/fonts/woff2/IRANSansWeb.woff2" as="font" crossOrigin="" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;400;700;900&display=swap" rel="stylesheet"></link>
      </Head>
      <Div>
        <h1>
          <Fa>به وبسایت جدید درسون خوش آمدید.</Fa>
          <En>Welcome to the Darsoon's new website.</En>
        </h1>
        <p className="center-text">
          <Fa>در دست ساخت.</Fa>
          <En>Corrently under development.</En>
        </p>

        <p>
          <Link href="/become-a-teacher">
            <a className="center-item">
              <En>Join us as a teacher</En>
              <Fa>به معلم‌های درسون بپیوندید!</Fa>
            </a>
          </Link>
        </p>
      </Div>
    </>
  );
}

const Div = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  gap: 3rem;
`;
